apiVersion: v1
kind: Secret
metadata:
  namespace: paas-prow
  name: github-token
stringData:
  #  bot personal token
  # Generated according to https://github.com/kubernetes/test-infra/blob/ff1bf8b1a1bc6df2cfb9b446fdc353e268a00bad/prow/getting_started_deploy.md#github-bot-account
   token: {{.Token}} 
---
apiVersion: v1
kind: Secret
metadata:
  namespace: paas-prow
  name: hmac-token
stringData:
  # Generate via `openssl rand -hex 20`. This is the secret used in the GitHub webhook configuration
  hmac: {{ .HMAC }}
